# Generated by Django 4.0.2 on 2022-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0002_buses_range_of_vehicle_remove_car_ticket_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_details',
            name='seats',
            field=models.CharField(max_length=4),
        ),
    ]
