# Generated by Django 4.0.2 on 2022-05-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0003_alter_ticket_details_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
