# Generated by Django 4.0.2 on 2022-05-18 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketapp', '0004_buses_active_car_active_ticket_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='active',
        ),
        migrations.RemoveField(
            model_name='car',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='active',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('Ticket_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Ticketapp.ticket_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
